%% ACOTA Y REDONDEA LOS VALORES INGRESADOS

% OPERACION DEDICADA PARA ESTA APLICACION
% TRANSFORMA EL CERO DE LAS MEDICIONES DE ANGULO A LA MITAD DE UN BYTE 
% ES DECIR:  (0° = 1278) 
% LUEGO ACOTA A LOS VALORES MAXIMOS Y MINIMOS INGRESADOS
% POR ULTIMO REDONDEA AL ENTERO MAS CERCANO.

function [ACOTADO] = COTA(VALOR,MAXIMO,MINIMO)

VAL_MEDIO = 127;
ACOTADO = VAL_MEDIO + VALOR;

if (VALOR > MAXIMO)
	ACOTADO = VAL_MEDIO + MAXIMO;
elseif (VALOR < MINIMO)
	ACOTADO = VAL_MEDIO + MINIMO;
end

ACOTADO = round(ACOTADO);

end

